services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      HOST: find_job_postgres
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups

networks:
  default:
    external: true
    name: find_job_network
